### ISSUE TITLE
about roadmap

### ISSUE THREAD

**Issue by laopeng2021** [Acxiom/metalus#201]
Is metalus already used in a real production environment?
Because in the trial process, I found that there are still many bugs.
How is the next step planned? Thank you

**Comment by dafreels** [comment]
Metalus has been in production for several years. Please join the [Slack channel](https://join.slack.com/t/acxiom-metalus/shared_invite/enQtODY3OTU0ODE5NzUwLTc2Zjc0MzE2MjYzZjBmZjJkODQxODhhOTM4N2VmZjNhZGVlN2Q3N2QzNWU3ZTk4NWExNWM2YzZkYTVjNjNiNWQ) and post any question/problems. Someone should be able to help solve any issues that you are encountering.
