### ISSUE TITLE
Inline string concatenation does not work 

### ISSUE THREAD

**Issue by ntallapa12** [Acxiom/metalus#238]
I am trying to concat two strings from previous steps and its failing, below are the details

Inline concatenation string
`@{GetTargetTableDatabase}-@{GetTargetTableName}`
This is the error message I get
`Value for @{GetTargetTableName} is an object. String concatenation will be ignored.`

**Comment by djfreels** [comment]
Adding details, this issue occurs when passing an Option wrapped in an Option, so `DefaultPipelineStepResponse(Some(Some(myString)),None)`. We parse both options when passing the parameter to a step, but fail to parse the second Option for the inline concatenation.
